### ISSUE TITLE
pre trained model

### ISSUE THREAD

**Issue by SaddamBInSyed** [ClearSpear/cameramouse#2]
@ClearSpear 

thanks for your work.

could you please upload the model which you are using in the code.?
also, I am curious to see this demo video, can u please post any recorded video in order to understand how this code works in realtime?

thanks

**Comment by clearspear** [comment]
Unfortunately, I no longer am in the same location as when I was when I worked on this project, but hopefully the files I just uploaded are the correct files. The demo was a live demo for a private group, so there is no recording currently.
